### ISSUE TITLE
Add side view of anglers chosen as you select them for tournaments

### ISSUE THREAD

**Issue by ceegarnut** [envasquez/SABC#119]
And as you select them, they fall of the list for the next selection.

**Comment by envasquez** [comment]
I believe I fixed this by removing the names from choices as you add them. So it should be impossible to double add an Angler.

Do you still really want this feature? You can always hit the "Back" button after you save. And that will show you real time results as you save them.

If you REALLY REALLY want this, then reopen the issue and I will add it to the UI redesign milestone.

**Comment by ceegarnut** [comment]
I’m good Chris AnnoniAustin, TX512-289-5477 CellSent from my iPhone 7On Feb 18, 2023, at 11:40 AM, envasquez ***@***.***> wrote:﻿
I believe I fixed this by removing the names from choices as you add them. So it should be impossible to double add an Angler.
Do you still really want this feature? You can always hit the "Back" button after you save. And that will show you real time results as you save them.
If you REALLY REALLY want this, then reopen the issue and I will add it to the UI redesign milestone.
