### ISSUE TITLE
Add ability to forward all maps shown on website to a cellphone

### ISSUE THREAD

**Issue by ceegarnut** [envasquez/SABC#126]
A nice feature would be to have the ability to send the map to cellphone so you can you use cellphone GPS to get you to the lake, or Beto's, etc.

**Comment by envasquez** [comment]
I don't think I can do this (currently).
Its really just a couple of clicks:
1. Click "View Larger Map"
2. Click "Send to Phone"
3. Enter your phone number

**Comment by ceegarnut** [comment]
Yeah, that is easy to explain to users.
Thanks amigo!
Chris
    On Friday, February 17, 2023 at 08:49:04 PM CST, envasquez ***@***.***> wrote:  
 
 


I don't think I can do this (currently).
Its really just a couple of clicks:
   
   - Click "View Larger Map"
   - Click "Send to Phone"
   - Enter your phone number
